### ISSUE TITLE
unexpected behaviour after using DISTINCT keyword in query

### ISSUE THREAD

**Issue by keesterbrugge** [dbcli/athenacli#32]
When connected to a database I type 

``` sql
SELECT DISTINCT
```
and then hit space I get 

``` 
SELECT DISTINCT Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/athenacli/0.1.3/libexec/lib/python3.7/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/Cellar/athenacli/0.1.3/libexec/lib/python3.7/site-packages/athenacli/completer.py", line 217, in get_completions
    matcher = self.suggestion_matchers[suggestion_type]
KeyError: <class 'list'>
```

If instead I first open a `(` I am able to continue typing the query. 

Thanks for this great product. I use it every day :)

**Comment by zzl0** [comment]
@keesterbrugge I am glad you like it and thanks for your feedback. I will take a look this today or tomorrow.

**Comment by zzl0** [comment]
@keesterbrugge Can you try `athenacli 0.1.4`? and see if it works.

**Comment by zzl0** [comment]
Feel free to open it if it doesn't work for you.
