### ISSUE TITLE
Throwing KeyError: 'work_group'

### ISSUE THREAD

**Issue by rayne-hernandez** [dbcli/athenacli#68]
Athenacli recently started throwing `KeyError: 'work_group'` upon usage. I installed using `pip` using python 3.7.7 installed with `pyenv`. Here are some details

```
> pip show athenacli
Name: athenacli
Version: 1.6.1
Summary: CLI for Athena Database. With auto-completion and syntax highlighting.
Home-page: https://github.com/dbcli/athenacli
Author: athenacli Core Team
Author-email: athenacli@googlegroups.com
License: UNKNOWN
Location: /Users/raynehernandez/.pyenv/versions/3.7.7/lib/python3.7/site-packages
Requires: prompt-toolkit, configobj, PyAthena, cli-helpers, botocore, sqlparse, boto3, Pygments, click
Required-by: 
```

```
> athenacli --profile <profile>
Traceback (most recent call last):
  File "/Users/xxxx/.pyenv/versions/3.7.7/bin/athenacli", line 8, in <module>
    sys.exit(cli())
  File "/Users/xxxx/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxxx/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xxxx/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxxx/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xxxx/.pyenv/versions/3.7.7/lib/python3.7/site-packages/athenacli/main.py", line 653, in cli
    database=database
  File "/Users/xxxx/.pyenv/versions/3.7.7/lib/python3.7/site-packages/athenacli/main.py", line 74, in __init__
    aws_access_key_id, aws_secret_access_key, region, s3_staging_dir, work_group, profile, _cfg
  File "/Users/xxxx/.pyenv/versions/3.7.7/lib/python3.7/site-packages/athenacli/config.py", line 36, in __init__
    self.work_group = self.get_val(work_group, _cfg['work_group'])
  File "/Users/xxxx/.pyenv/versions/3.7.7/lib/python3.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'work_group'
```

**Comment by zzl0** [comment]
Hey @rayne-hernandez could you try to add below line in your [AthenaCLI config file](https://github.com/dbcli/athenacli#config).

`work_group = 'primary'`

This was a feature introduced in version `1.6.0`.

**Comment by zzl0** [comment]
Feel free to re-open this if the above solution does not work for you.
